# SPDX-FileCopyrightText: Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(mha)
add_subdirectory(silu)
add_subdirectory(rms_norm)
add_subdirectory(elementwise_mul)
add_subdirectory(elementwise_add)
add_subdirectory(rope)
add_subdirectory(softmax)
add_subdirectory(matrix_vector_mul)
add_subdirectory(gemm)
add_subdirectory(layer_norm)
add_subdirectory(relu)
add_subdirectory(gelu)
add_subdirectory(mem_copy)
add_subdirectory(swiglu)
